=== ljayacha/XML-XSD/buildings.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="BuildingTable" type="BuildingTableType"></xs:element>

	<xs:complexType name="BuildingTableType">
		<xs:sequence>
			<xs:element ref="Building" maxOccurs="unbounded"></xs:element>
		</xs:sequence>
	</xs:complexType>


	<xs:element name="Building">
		<xs:complexType mixed="true">
			<xs:sequence>
				<xs:element name="Code">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:pattern value="[A-Z][A-Z][A-Z]" />
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="BuildingName" type="xs:string" />
				<xs:element name="Position">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Latitude">
								<xs:simpleType>
									<xs:restriction base="xs:decimal">
										<xs:fractionDigits value="6" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="Longitude">
								<xs:simpleType>
									<xs:restriction base="xs:decimal">
										<xs:fractionDigits value="6" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Address" maxOccurs="1" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="StreetNo" type="xs:integer" />
							<xs:element name="StrName" type="xs:string" />
							<xs:element name="City" type="xs:string" />
							<xs:element name="State">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:pattern value="[A-Z][A-Z]" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="Zip">
								<xs:simpleType>
									<xs:restriction base="xs:integer">
										<xs:pattern value="[0-9][0-9][0-9][0-9][0-9]" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== ljayacha/XML-XSD/buildings.xml
<?xml version="1.0" encoding="UTF-8"?>

<BuildingTable
	xsi:noNamespaceSchemaLocation="buildings.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<Building>

		<Code>KOH</Code>
		
		<BuildingName>King Olympic Hall</BuildingName>
		
		<Position>
			
			<Latitude>34.024547</Latitude>
			
			<Longitude>-118.288</Longitude>
		
		</Position>
		
		<Address>
			
			<StreetNo>1027</StreetNo>
			
			<StrName>W 34th St</StrName>
			
			<City>Los Angeles</City>
			
			<State>CA</State>
			
			<Zip>90007</Zip>
		
		</Address>
	
	</Building>

	<Building>

		<Code>CFX</Code>

		<BuildingName>Cromwell Field</BuildingName>

		<Position>

			<Latitude>34.021631</Latitude>

			<Longitude>-118.289</Longitude>

		</Position>

		<Address>

			<StreetNo>1026</StreetNo>

			<StrName>W 34th St</StrName>

			<City>Los Angeles</City>

			<State>CA</State>

			<Zip>90089</Zip>

		</Address>

	</Building>


	<Building>

		<Code>JEP</Code>

		<BuildingName>JEP House</BuildingName>


		<Position>

			<Latitude>34.022947</Latitude>

			<Longitude>-118.284</Longitude>

		</Position>


		<Address>

			<StreetNo>801</StreetNo>

			<StrName>W 34th St</StrName>

			<City>Los Angeles</City>

			<State>CA</State>

			<Zip>90089</Zip>

		</Address>

	</Building>


	<Building>

		<Code>SHC</Code>

		<BuildingName>Student Health Center</BuildingName>


		<Position>

			<Latitude>34.023303</Latitude>

			<Longitude>-118.285</Longitude>

		</Position>


		<Address>

			<StreetNo>849</StreetNo>

			<StrName>W 34th St</StrName>

			<City>Los Angeles</City>

			<State>CA</State>

			<Zip>90089</Zip>

		</Address>

	</Building>


	<Building>

		<Code>LVY</Code>

		<BuildingName>Leavey Library</BuildingName>


		<Position>

			<Latitude>34.021595</Latitude>

			<Longitude>-118.282</Longitude>

		</Position>


		<Address>

			<StreetNo>651</StreetNo>

			<StrName>W 35th St</StrName>

			<City>Los Angeles</City>

			<State>CA</State>

			<Zip>90089</Zip>

		</Address>

	</Building>


	<Building>

		<Code>VKC</Code>

		<BuildingName>Von KleinSmid Center</BuildingName>


		<Position>

			<Latitude>34.021649</Latitude>

			<Longitude>-118.284</Longitude>

		</Position>


		<Address>

			<StreetNo>3518</StreetNo>

			<StrName>Trousdale</StrName>

			<City>Los Angeles</City>

			<State>CA</State>

			<Zip>90089</Zip>

		</Address>

	</Building>


	<Building>

		<Code>WPH</Code>

		<BuildingName>Waite Phillips Hall</BuildingName>


		<Position>

			<Latitude>34.022289</Latitude>

			<Longitude>-118.284</Longitude>

		</Position>


		<Address>

			<StreetNo>3550</StreetNo>

			<StrName>Trousdale</StrName>

			<City>Los Angeles</City>

			<State>CA</State>

			<Zip>90089</Zip>

		</Address>

	</Building>


	<Building>

		<Code>JHH</Code>

		<BuildingName>John Hubbard Hall</BuildingName>


		<Position>

			<Latitude>34.020101</Latitude>

			<Longitude>-118.284</Longitude>

		</Position>


		<Address>

			<StreetNo>615</StreetNo>

			<StrName>Childs Way</StrName>

			<City>Los Angeles</City>

			<State>CA</State>

			<Zip>90089</Zip>

		</Address>

	</Building>


	<Building>

		<Code>REG</Code>

		<BuildingName>Registration Builing</BuildingName>


		<Position>

			<Latitude>34.019603</Latitude>

			<Longitude>-118.282</Longitude>

		</Position>


		<Address>

			<StreetNo>611</StreetNo>

			<StrName>Childs Way</StrName>

			<City>Los Angeles</City>

			<State>CA</State>

			<Zip>90089</Zip>

		</Address>

	</Building>


	<Building>

		<Code>STU</Code>

		<BuildingName>Student Union</BuildingName>


		<Position>

			<Latitude>34.020226</Latitude>

			<Longitude>-118.286</Longitude>

		</Position>


		<Address>

			<StreetNo>3551</StreetNo>

			<StrName>Trousdale</StrName>

			<City>Los Angeles</City>

			<State>CA</State>

			<Zip>90089</Zip>

		</Address>

	</Building>


	<Building>

		<Code>BKS</Code>

		<BuildingName>Bookstore</BuildingName>


		<Position>

			<Latitude>34.020635</Latitude>

			<Longitude>-118.286</Longitude>

		</Position>


		<Address>

			<StreetNo>840</StreetNo>

			<StrName>Childs Way</StrName>

			<City>Los Angeles</City>

			<State>CA</State>

			<Zip>90089</Zip>

		</Address>

	</Building>


	<Building>

		<Code>RTH</Code>

		<BuildingName>Ronald Tutor Hall</BuildingName>


		<Position>

			<Latitude>34.020137</Latitude>

			<Longitude>-118.29</Longitude>

		</Position>


		<Address>

			<StreetNo>3710</StreetNo>

			<StrName>McClintock</StrName>

			<City>Los Angeles</City>

			<State>CA</State>

			<Zip>90089</Zip>

		</Address>

	</Building>

	<Building>

		<Code>SAL</Code>

		<BuildingName>Salvatori Com. Center</BuildingName>


		<Position>

			<Latitude>34.01955</Latitude>

			<Longitude>-118.289</Longitude>

		</Position>


		<Address>

			<StreetNo>941</StreetNo>

			<StrName>W 37th Place</StrName>

			<City>Los Angeles</City>

			<State>CA</State>

			<Zip>90089</Zip>

		</Address>

	</Building>


	<Building>

		<Code>EEB</Code>

		<BuildingName>Electrical Engr Center</BuildingName>


		<Position>

			<Latitude>34.019728</Latitude>

			<Longitude>-118.29</Longitude>

		</Position>


		<Address>

			<StreetNo>3715</StreetNo>

			<StrName>McClintock</StrName>

			<City>Los Angeles</City>

			<State>CA</State>

			<Zip>90089</Zip>

		</Address>

	</Building>


	<Building>

		<Code>OHE</Code>

		<BuildingName>Olin Hall Engineering</BuildingName>


		<Position>

			<Latitude>34.020493</Latitude>

			<Longitude>-118.29</Longitude>

		</Position>


		<Address>

			<StreetNo>3650</StreetNo>

			<StrName>McClintock</StrName>

			<City>Los Angeles</City>

			<State>CA</State>

			<Zip>90089</Zip>

		</Address>

	</Building>

</BuildingTable>
